version: '3.8'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd1
    ports:
      - "1433:1433"
